constants:
preferences:
  general:
    verbose: 0
  study:
    num_full_blocks: 2
    do_practice_block: false
    stim_transition_time_ms: 800 #milliseconds
    stim_static_time_ms: 400 #milliseconds
    full_block_sequence_length: 50
    practice_block_sequence_length:
    pre_full_block_break_time:
    pre_practice_block_break_time:
    stim_diameter:
    muse_signals:
      - EEG
      - PPG
      - Accelerometer
      - Gyroscope
  lsl:
    stream_markers_to_lsl:
    record_lsl:
    tcp_address:
    tcp_port:
