% lr = tcpip('localhost', 22345); 
% fopen(lr)
% fprintf(lr, 'select all');
% fprintf(lr, ['filename ' ...
%             '{task:MemoryGuided} ' ...
%             '{template:s_%p_%n.xdf ' ...
%             '{modality:ieeg}']); 
% fprintf(lr, 'start');

t = tcpclient('localhost', 22345, 'Timeout', 100)
writeline(t, 'select all')
writeline(t, ['filename ' ...
            '{task:MemoryGuided} ' ...
            '{template:s_%p_%n.xdf ' ...
            '{modality:ieeg}'])
writeline(t, 'start')