# See documentation for `src/config.py` for descriptions of attributes
constants:
  path_to_LabRecorder: lib/LabRecorder/LabRecorder.exe
preferences:
  general:
    verbose: 3
  study:
    num_full_blocks: 3
    do_practice_block: True
    stim_transition_time_ms: 800 #milliseconds
    stim_static_time_ms: 400 #milliseconds
    full_block_sequence_length: 500
    practice_block_sequence_length: 50
    pre_full_block_break_time: 120 #seconds
    pre_practice_block_break_time: 30 #seconds
    stim_diameter: 1000
    muse_signals:
      - EEG
      - PPG
      - Accelerometer
      - Gyroscope
  lsl:
    stream_markers_to_lsl: True
    record_lsl: True
    tcp_address: localhost
    tcp_port: 22345